# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui2.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(767, 600)
        MainWindow.setStyleSheet("*{\n"
"font-family:Verdana\n"
"}\n"
"\n"
"#biggy_frame{\n"
"background:rgb(0, 65, 98)\n"
"}\n"
"QFrame{\n"
"background:#007f5d;\n"
"border-radius:8px;\n"
"}\n"
"\n"
"#small_frame{\n"
"background:white;\n"
"border-radius:20px;\n"
"}\n"
"\n"
"#speak{\n"
"color: white;\n"
"font: 24px;\n"
"background:transparent\n"
"}\n"
"\n"
"#button{\n"
"background:white;\n"
"border-radius: 20px;\n"
"}\n"
"\n"
"#nex{\n"
"background:white;\n"
"color:rgb(0, 103, 74);\n"
"font:24px;\n"
"border-radius:15px;\n"
"}\n"
"\n"
"#toolButton{\n"
"background:transparent\n"
"}\n"
"\n"
"#text_label{\n"
"color:rgb(70, 70, 70);\n"
"background:transparent;\n"
"border:1px solid #007f5d;\n"
"font-size:18px;\n"
"}\n"
"\n"
"#text_label_2{\n"
"background: none;\n"
"font-size: 18px;\n"
"color:rgb(138, 138, 138);\n"
"border: 1px solid rgb(50, 0, 150)\n"
"}\n"
"\n"
"#text_edit1{\n"
"color:white;\n"
"background-color:rgba(58, 58, 58, 50)\n"
"}\n"
"\n"
"#user_says{\n"
"font-size: 15px;\n"
"color: white;\n"
"background:rgb(116, 116, 116);\n"
"border-radius:6px;\n"
"}\n"
"#response{\n"
"font-size: 15px;\n"
"color: white;\n"
"background:rgb(116, 116, 116);\n"
"border-radius:6px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.biggy_frame = QtWidgets.QFrame(self.centralwidget)
        self.biggy_frame.setGeometry(QtCore.QRect(0, 0, 791, 581))
        self.biggy_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.biggy_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.biggy_frame.setObjectName("biggy_frame")
        self.small_frame = QtWidgets.QFrame(self.biggy_frame)
        self.small_frame.setGeometry(QtCore.QRect(370, 10, 391, 551))
        self.small_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.small_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.small_frame.setObjectName("small_frame")
        self.text_label = QtWidgets.QLabel(self.small_frame)
        self.text_label.setGeometry(QtCore.QRect(10, 70, 371, 91))
        self.text_label.setWordWrap(True)
        self.text_label.setObjectName("text_label")
        self.text_label_2 = QtWidgets.QLabel(self.small_frame)
        self.text_label_2.setGeometry(QtCore.QRect(10, 220, 371, 321))
        self.text_label_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.text_label_2.setScaledContents(True)
        self.text_label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.text_label_2.setWordWrap(True)
        self.text_label_2.setIndent(0)
        self.text_label_2.setObjectName("text_label_2")
        self.user_says = QtWidgets.QLabel(self.small_frame)
        self.user_says.setGeometry(QtCore.QRect(280, 30, 101, 31))
        self.user_says.setObjectName("user_says")
        self.response = QtWidgets.QLabel(self.small_frame)
        self.response.setGeometry(QtCore.QRect(10, 180, 101, 31))
        self.response.setObjectName("response")
        self.speak = QtWidgets.QLabel(self.biggy_frame)
        self.speak.setGeometry(QtCore.QRect(60, 500, 241, 51))
        self.speak.setObjectName("speak")
        self.button = QtWidgets.QPushButton(self.biggy_frame)
        self.button.setGeometry(QtCore.QRect(110, 500, 61, 61))
        self.button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/R/Downloads/download (2).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button.setIcon(icon)
        self.button.setIconSize(QtCore.QSize(45, 45))
        self.button.setObjectName("button")
        self.nex = QtWidgets.QLabel(self.biggy_frame)
        self.nex.setGeometry(QtCore.QRect(10, 40, 351, 71))
        self.nex.setObjectName("nex")
        self.toolButton = QtWidgets.QToolButton(self.biggy_frame)
        self.toolButton.setGeometry(QtCore.QRect(190, 10, 211, 131))
        self.toolButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("C:/Users/R/Downloads/bot1.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon1)
        self.toolButton.setIconSize(QtCore.QSize(80, 100))
        self.toolButton.setObjectName("toolButton")
        self.text_edit1 = QtWidgets.QTextEdit(self.biggy_frame)
        self.text_edit1.setGeometry(QtCore.QRect(40, 150, 291, 301))
        self.text_edit1.setObjectName("text_edit1")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.text_label.setText(_translate("MainWindow", "This is what the user speaks"))
        self.text_label_2.setText(_translate("MainWindow", "This is for the engine's execution"))
        self.user_says.setText(_translate("MainWindow", "  User said:"))
        self.response.setText(_translate("MainWindow", "Response:"))
        self.speak.setText(_translate("MainWindow", "Tap          Speak"))
        self.nex.setText(_translate("MainWindow", " Nexus"))
        self.text_edit1.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Verdana\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Introducing Nexus. Your  personal virtual assistant</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\"> Nexus is capable of doing  your daily tasks for you for example telling the time, date, weather, information about anything and so much more </span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\"> To start Nexus, tap the  button below</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
